//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int id { get; set; }
        public string maHoaDon { get; set; }
        public System.DateTime thoiGianLap { get; set; }
        public decimal tongTien { get; set; }
        public string maKhachHang { get; set; }
        public string maNhanVienLap { get; set; }
        public string maPhong { get; set; }
        public string maKhuyenMai { get; set; }
        public Nullable<int> daXoa { get; set; }
    
        public virtual DanhSachMaKhuyenMai DanhSachMaKhuyenMai { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
