//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int id { get; set; }
        public string maPhong { get; set; }
        public string soPhong { get; set; }
        public string loaiPhong { get; set; }
        public int tinhTrang { get; set; }
        public int daXoa { get; set; }
        public string bangGia { get; set; }
        public string maKhachHang { get; set; }
        public string ghiChu { get; set; }
        public Nullable<System.DateTime> thoiGianBatDau { get; set; }
    
        public virtual DanhSachBangGia DanhSachBangGia { get; set; }
        public virtual DanhSachLoaiPhong DanhSachLoaiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
